# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Excel2Mapa
                                 A QGIS plugin
 Genera un mapa tomando datos de un archivo excel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-20
        copyright            : (C) 2025 by INEGI
        email                : emmanuel.rodriguez@inegi.org.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Excel2Mapa class from file Excel2Mapa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .excel2mapa import Excel2Mapa
    return Excel2Mapa(iface)
