# -*- coding: utf-8 -*-
"""
/***************************************************************************
 excel2mapa
                                 A QGIS plugin
 Genera una composicion de un mapa obteniendo los datos de un arcchivo excel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-08
        copyright            : (C) 2025 by INEGI
        email                : emmanuel.rodriguez@inegi.org.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load excel2mapa class from file excel2mapa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .excel2mapa import excel2mapa
    return excel2mapa(iface)
